services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:latest
    container_name: fedlorasemble-tgi
    ports:
      - "8080:80"
    environment:
      - MODEL_ID=/data/models/qwens/Qwen2.5-0.5B-Instruct
      - MAX_CONCURRENT_REQUESTS=128
      - CUDA_MEMORY_FRACTION=0.8
      - MAX_BATCH_SIZE=32
      - MAX_BATCH_PREFILL_TOKENS=4096
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../../models:/data/models
    device_requests:
      - driver: nvidia
        count: 1
        capabilities: [gpu]
    restart: unless-stopped
